version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: draf2/docs/requirements.txt

sphinx:
  configuration: draf2/docs/docs/source/conf.py