# Generated by Django 4.1 on 2023-08-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('enhancerid', models.CharField(db_column='enhancerId', max_length=255, primary_key=True, serialize=False)),
                ('chr', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('source', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'interactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactionsxgenexsnps',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interactionsXgeneXsnps',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Enhancers',
        ),
        migrations.DeleteModel(
            name='Enhancersxsnps',
        ),
        migrations.DeleteModel(
            name='Enhancerxgene',
        ),
    ]
