name: SNEEP
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.1.2=py311h06a4308_0
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinx_rtd_theme=0.4.3=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.5=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.4=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.9=pyhd8ed1ab_0
  
  - pip:
    - httpcore==0.17.3
    - httpie==3.2.2
    - httpx==0.24.1
    - markdown-it-py==3.0.0
   

